version: '3.8'

services:

  evcsfinder-db:
    build:
      context: ./EVCSFinderDb
    container_name: evcsfinder-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend
    restart: always
    environment:
      - FORCE_LOAD=${FORCE_LOAD:-false}

  evcsfinder-service:
    build: ./EVCSFinderService
    container_name: evcsfinder-service
    ports:
      - "5000:5000"
    depends_on:
      - evcsfinder-db
    networks:
      - backend
    environment:
      DATABASE_URL: mongodb://evcsfinder-db:27017/ev_charging
    volumes:
      - ocm-data:/data
      - ./EVCSFinderService/src:/app/src

  evcsfinder-app:
    build:
      context: ./EVCSFinderApp
      args:
        REACT_APP_API_URL: http://localhost:5000
    container_name: evcsfinder-app
    ports:
      - "3000:3000"
    depends_on:
      - evcsfinder-service
    networks:
      - backend
    volumes:
      - ./EVCSFinderApp/src:/app/src
      - ./EVCSFinderApp/public:/app/public
  
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongo-data:
  ocm-data:

networks:
  backend:
    driver: bridge
