---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: evcsfinder
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: http
...