apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: evcsfinder
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: evcsfinder
        tier: backend
        track: stable
    spec:
      containers:
      - name: evcsfinder-service
        image: masoodav/evcsfinder-service:latest
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: DATABASE_URL
          value: mongodb://database:27017/ev_charging
        volumeMounts:
        - name: ocm-data
          mountPath: /data
      volumes:
      - name: ocm-data
        persistentVolumeClaim:
          claimName: ocm-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocm-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
