---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: evcsfinder
      tier: database
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: evcsfinder
        tier: database
        track: stable
    spec:
      containers:
      - name: evcsfinder-db
        image: masoodav/evcsfinder-db:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        env:
        - name: FORCE_LOAD
          value: "true"
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
...